<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'moonlightcotton');
define('_DB_USER_', 'root');
define('_DB_PASSWD_', 'm4w351');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'qW3JNLKwIuyQY6cDJRhXuTERB4PXzXqrOBs6WrqneoAmYzDiwE7F3qss');
define('_COOKIE_IV_', 'zbncZphB');
define('_PS_CREATION_DATE_', '2014-09-16');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', 'Coo2i3qvHd0ZfUAqRwtZF5DKi9nuBgPr');
define('_RIJNDAEL_IV_', '7JlXfgCGjcVJfJ289KUc9Q==');
